version: '3.7'

services:

  fleet_database:
    build: ./mysql_fleet_database
    container_name: fleet_database
    restart: always
    env_file:
      - ./.env
    volumes:
      - ./mysql_fleet_database/db_fleet_data:/var/lib/mysql
    ports:
      - 3306:3306
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 5s
      timeout: 5s
      retries: 10

  data_gathering_service:
    build: ./data_gathering
    container_name: data_gathering_service
    restart: always
    volumes:
      - ./data_gathering/:/app/
    ports:
      - 8001:8000
    env_file:
      - ./.env
    depends_on:
      fleet_database:
        condition: service_healthy

  report_service:
    build: ./report
    container_name: report_service
    ports:
      - 8888:8888
    volumes:
      - ./report/dist/:/usr/src/app/dist/
      - ./report/src/:/usr/src/app/src/

  #nginx_report_service:
  #  image: nginx:latest
  #  container_name: nginx_report_service
  #  ports:
  #    - "8888:80"
  #  volumes:
  #    - ./report/dist:/usr/share/nginx/html
  #  depends_on:
  #    build_report_service:
  #      condition: service_completed_successfully

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "8080:8080"
    volumes:
      - ./nginx_config.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - data_gathering_service
